// Generated by create-devil-app — AdSense placeholder
// Replace with real AdSense script when ready

export default function AdSlot({ className = '' }: { className?: string }) {
  return (
    <div className={`ads-slot ${className}`}>
      {/* AdSense */}
      <span className="ads-placeholder">Advertisement</span>
    </div>
  );
}
