'use client';
// Generated by create-devil-app — Mock payment modal

interface PaymentModalProps {
  onUpgrade: () => void;
  onClose: () => void;
  t: { premiumTitle: string; premiumDesc: string; upgrade: string; cancel: string };
}

export default function PaymentModal({ onUpgrade, onClose, t }: PaymentModalProps) {
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-box glass-panel" onClick={(e) => e.stopPropagation()}>
        <h2 className="modal-title">👑 {t.premiumTitle}</h2>
        <p className="modal-desc">{t.premiumDesc}</p>
        <button className="btn-primary modal-btn" onClick={onUpgrade}>{t.upgrade}</button>
        <button className="modal-cancel" onClick={onClose}>{t.cancel}</button>
      </div>
    </div>
  );
}
